# Generated by Django 5.2.4 on 2025-10-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeproductmodel',
            options={'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.RemoveIndex(
            model_name='photoproductmodel',
            name='product_pho_product_90602a_idx',
        ),
    ]
