### Register User
POST {{path}}api/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "asdd@gmail.com",
  "password": "rootroot"
}


### Login User
POST {{path}}api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "asdd@gmail.com",
  "password": "rootroot"
}

> {%
    client.global.set("csrftoken", response.headers.valuesOf("Set-Cookie").find(cookie => cookie.includes("csrftoken")).split("=")[1].split(";")[0]);
    client.global.set("sessionid", response.headers.valuesOf("Set-Cookie").find(cookie => cookie.includes("sessionid")).split("=")[1].split(";")[0]);
%}

### Logout User (with variables)
GET {{path}}api/user/logout/
Cookie: csrftoken={{csrftoken}}; sessionid={{sessionid}}
X-CSRFToken: {{csrftoken}}

> {%
    client.global.clear("csrftoken");
    client.global.clear("sessionid")
%}

### Logout User (simple)
GET {{path}}api/user/logout/
